#!/system/bin/sh
mount -o rw,remount /
mkdir /system/system_ext/priv-app/ThermalBoost
cp perf /system/system_ext/priv-app/ThermalBoost/ThermalBoost.apk
chmod 644 /system/system_ext/priv-app/ThermalBoost/ThermalBoost.apk
