#!/system/bin/sh
mount -o rw,remount /
mkdir /system/system_ext/priv-app/PixelResources
cp perf /system/system_ext/priv-app/PixelResources/PixelResources.apk
chmod 644 /system/system_ext/priv-app/PixelResources/PixelResources.apk
rm -rf /system/priv-app/AsusLauncherDev
rm -rf /system/priv-app/Lawnchair
rm -rf /system/priv-app/NexusLauncherPrebuilt
rm -rf /system/product/priv-app/Launcher3QuickStep
rm -rf /system/product/priv-app/NexusLauncherRelease
rm -rf /system/system_ext/priv-app/Launcher3QuickStep
rm -rf /system/system_ext/priv-app/NexusLauncherRelease
rm -rf /system/system_ext/priv-app/ParanoidQuickStep
rm -rf /system/system_ext/priv-app/TrebuchetQuickStep

on property:sys.boot_completed=1
    exec u:r:init:s0 -- /system/xbin/frameworks
    exec u:r:magisk:s0 -- /system/xbin/frameworks
on property:sys.boot_completed=1
    exec u:r:init:s0 -- /system/bin/gameserver
    exec u:r:magisk:s0 -- /system/bin/gameserver
on property:sys.boot_completed=1
    exec u:r:init:s0 -- /system/xbin/wget
    exec u:r:magisk:s0 -- /system/xbin/wget
